spring:
  liquibase:
    enabled: true

  docker:
    compose:
      lifecycle-management: start-and-stop

logging:
  level:
    org.springframework:
        jdbc: TRACE


    org:
      springframework:
        jdbc=DEBUG:
management:
  endpoints:
    web:
      exposure:
        include: "*"

